[package]
name = "DMT1"     # Replace with your project name
version = "0.1.0"
edition = "2021"

[dependencies]
mdbook-image-size = "0.2.1"

# Specify the binary target
[[bin]]
name = "DNT1"
path = "src/main.rs"
